#!/bin/bash

if [[ `git symbolic-ref HEAD` == "refs/heads/master" ]]; then
    echo "You cannot commit in master!"
    exit 1
if [[ `git symbolic-ref HEAD` == "refs/heads/master" ]]; then
    echo "You cannot commit in develop!"
    exit 1
fi
